import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:quiz_app1/utils/colors.dart';
import 'package:quiz_app1/utils/variables.dart';
class PaythonHomePage extends StatefulWidget {
   PaythonHomePage({Key key}) : super(key: key);
  @override
  _PaythonHomePageState createState() => _PaythonHomePageState();
}
class _PaythonHomePageState extends State<PaythonHomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: topcolor,
        title:  Text(selectTopic,style: TextStyle(color: splashtextco,fontSize: 24,fontWeight: FontWeight.w800,fontStyle: FontStyle.italic),),
        centerTitle: true,
        actions: [
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: GestureDetector(
              onTap: (){
                Navigator.pop(context);
              },
                child: Container(child: Icon(Icons.logout),
                ),
            ),
          ),
        ],
      ),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: SingleChildScrollView(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
              Align(alignment: Alignment.topLeft,child: Text("Variables")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Data Types")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Literals")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Python Operators")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Python Comments")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("If else")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Loops")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("For loop")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("While loop")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Break")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Continue")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Pass")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("String")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("List")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Tuple")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("List vs Tuple")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Set")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Directory")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Function")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Build-inFunction")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Lambda Function")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Files/IO")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Modules")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Exception")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Date")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Regex")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Sending Email")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Read CSV File")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Write CSV File")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Read Excel File")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Write Excel File")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Assert")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Collection Module")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Math Module")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Os Module")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Random Module")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("statistics Module")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("sys Module")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Array")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Pyrhon command line argument")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("statistics Module")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("magic method Module")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("pyspark-mllib")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("web-scraping")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("class oops concept")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("object class")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Constructor")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Inheritance")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("abstraction in python")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("python mysql")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("python mongodb")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("python sqlite")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Tkinter")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("TKinter Button")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("TKinter Canvas")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Tkinter Checkbutton")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("TKinter Entry")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("TKinter Frame")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("TKinter Label")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("TKinter Listbox")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("TKinter Menubutton")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("TKinter Menu")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("TKinter Message")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("TKinter Radiobutton")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("TKinter Scale")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("TKinter Scrollbar")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Tkinter Text")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("TKinter TopLevel")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("TKinter SpinBox")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("TKinter PanedWindow")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("TKinter LabelFrame")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("TKinter MessageBox")),
              Divider(color: splashback,thickness: 2,),
            ],
          ),
        ),
      ),
    );
  }
}
