import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';
import 'package:quiz_app1/utils/colors.dart';
import 'package:quiz_app1/utils/variables.dart';

class ChomePage extends StatefulWidget {
  const ChomePage({Key key}) : super(key: key);
  @override
  _ChomePageState createState() => _ChomePageState();
}

class _ChomePageState extends State<ChomePage> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        backgroundColor: topcolor,
        title:  Text(selectTopic,style: TextStyle(color: splashtextco,fontSize: 24,fontWeight: FontWeight.w800,fontStyle: FontStyle.italic),),
        centerTitle: true,
        actions: [
          Padding(
            padding: const EdgeInsets.all(8.0),
            child: GestureDetector(
              onTap: (){
                Navigator.pop(context);
              },
                child: Container(child: Icon(Icons.logout),
                ),
            ),
          ),
        ],
      ),
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: SingleChildScrollView(
          child: Column(
            mainAxisAlignment: MainAxisAlignment.start,
            crossAxisAlignment: CrossAxisAlignment.center,
            children: [
             // SizedBox(height: 50,),
              Align(alignment: Alignment.topLeft,child: Text("C History")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Features of C")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C program and compilation of c program")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("printf and scanf")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("variables")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Data types in c")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Keywords  in c")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("c indetifier")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("c operators")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("c comments")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("c formet specifier")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Escepe Sequence")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Asscii values")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("constants")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("literals")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("c Tokens")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Static ")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Programming error in c ")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Conditional Operator")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Bitwise Operator")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("if-else")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("switch")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C-Loops")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C-DoWhile loop")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C-While loop")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C-for loop")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Nested Loops in c")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C-Break")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C-continue")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C-goto")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C- Type Cating")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Function")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Call by value & reference Function")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Recursion")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("1-D Array")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("2-D Array")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Return Array")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Array Function")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C Pointer")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C Pointer to Pointer")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C Pointer Arithmetic")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Dangling Pointers in C")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Sizeof Pointers in C")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("constant Pointers in C")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Void Pointers in C")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C Difference Pointers in C")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Null Pointers in C")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C Function  Pointer")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C Function Pointer as a arguments")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C String")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C gets() & puts()")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C string Function")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C Maths Function")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C Structure")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("typedef in c")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C array structure")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C Nested Structure")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Structure padding in c")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C Union")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("File Handling")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C fprintf and fscanf")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C fputc and fgetc")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C fputs and fgets")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C fseek")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C rewind")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("C ftell")),
              Divider(color: splashback,thickness: 2,),
              Align(alignment: Alignment.topLeft,child: Text("Command line argument")),
              Divider(color: splashback,thickness: 2,),
            ],
          ),
        ),
      ),

    );
  }
}
